### ISSUE TITLE
Question abount inference

### ISSUE THREAD

**Issue by lbh666** [XiangZ-0/EVDI#10]
Hi, thanks for your great work about self-supervised learning of deblurring.I tried to run the inference code on the RBE example data.
`python Test.py --test_ts=0.5 --model_path=./PreTrained/EVDI-RBE.pth --test_path=./Database/RBE/ --save_path=./Result/EVDI-RBE/`
But the result is unsatisfying. The blurring remains the same([result](https://drive.google.com/file/d/1MIAxWqIcdlp3dzsR7combyuKrbJ0OXwa/view?usp=sharing) here).How can i deblur the RBE example data and reproduce the [gif](https://github.com/XiangZ-0/EVDI/blob/main/figs/upsample-RBE.gif) in this repo?
Looking forward to your reply. Thank you!

**Comment by XiangZ-0** [comment]
Hi lbh666, thank you for your interest in our work.

I just tried to run the inference command on the RBE data, but the result is correct on my side. I guess your result might be caused by some weird bugs during my recent updates. Could you please clone the latest repo (including codes and data) and try it again? If everything goes well, you are supposed to get a 'Result' folder like [this](https://drive.google.com/drive/folders/1QWpaopUb-fp5U7jaTGNTqKdpfldsfWiu?usp=share_link), where the subfolder 'Result/EVDI-RBE/Blur' contains the original blurry frames and 'Result/EVDI-RBE/Result' contains the deblurred result.

 If you want to generate the gif image, the easiest way is to change the attribute 'test_ts' from 0 to 1 to generate multiple deblurred results, and then convert them to a gif. For example, suppose you want to generate 10X frame-rate results, you can set test_ts=0.05, 0.1, 0.15, ... 1 and generate 20 results, then use functions like 'imageio.mimsave' to get the desired gif.

Hope this helps!

**Comment by lbh666** [comment]
Thanks for your timely reply. Unfortunately, i tried again and the reult remain the same.I used the [pretrained model](https://drive.google.com/drive/folders/1MIBQukoyK3_7lx3WZ4nB-PJqoRltb70B?usp=sharing) and changed nothing. Here is the [result](https://drive.google.com/file/d/1Q0eIEqliruvMyc9vW9hqY8w02wgbAiXB/view?usp=sharing) on my side. The result on both GoPro and GoPro-color is just fine.

**Comment by XiangZ-0** [comment]
Thanks for the feedback. I have tested your provided codes on different devices, but everything is ok, so weird. I wonder if it is caused by different versions of the required packages. Could you please provide the 'requirements.txt' of your environment so I could reproduce the result? Thx.

**Comment by lbh666** [comment]
I tried on RTX 3080 on Windows. The versions of packages are here.
`numpy==1.24, cv2==4.7, pytorch=2.0.1`
And i also tried on linux. The versions of packages are here.
`numpy==1.23.5, cv2==4.7, pytorch=2.0.0`
The result on Windows is shown [above](https://drive.google.com/file/d/1MIAxWqIcdlp3dzsR7combyuKrbJ0OXwa/view). The result on linux is the same as [the one you upload](https://drive.google.com/drive/folders/1QWpaopUb-fp5U7jaTGNTqKdpfldsfWiu?usp=share_link). Since the versions of packages are so close, I doubt if it's a system-dependent problem.
Anyway, thanks for yout patient answers and impressive work. Good luck!
